### ISSUE TITLE
天气领域BUG

### ISSUE THREAD

**Issue by u-bug-collector** [u-bug-collector/txz#1]
优先级：中     [高中低]
BUG描述： 先说“今天有大雪吗”返回后，再问“今天有大雨吗
返回结果： 也是返回的没有雪
期望： 返回没有雨
期望解决日期: 2016年8月12日

**Comment by sunxs1101** [comment]
fixes https://github.com/u-bug-collector/txz/issues/1

**Comment by gracecai888** [comment]
优先级：中 [高中低]
BUG描述：
唤醒语音说“吉林市天气怎么样”时，查询结果是“舒兰天气”查询结果错误
说“吉林省天气怎么样”时，查询结果为“吉林天气”
说“吉林天气怎么样”时，查询结果是长春天气
返回结果：
唤醒语音说“吉林市天气怎么样”时，查询结果应吉林天气
说吉林省或吉林天气怎么样时，应查询结果为长春天气
期望： 返回没有雨
期望解决日期: 2016年8月23日

**Comment by u-bug-collector** [comment]
fixes #1

**Comment by u-bug-collector** [comment]
fixes #1
