### ISSUE TITLE
关闭雷达在客户端解析的结果中name为APP_ALL

### ISSUE THREAD

**Issue by lvanli** [u-bug-collector/txz#10]
客户端请求的结果如下：
{"rc":0,"text":"关闭雷达","service":"cn.yunzhisheng.appmgr","code":"APP_EXIT","semantic":{"intent":{"name":"APP_ALL"}},"history":"cn.yunzhisheng.appmgr","responseId":"e0493340e6214af581eab7b4635dd6af"}
应该返回“雷达”这个应用关闭的场景

**Comment by u-bug-collector** [comment]
{"rc":0,"text":"关闭雷达","service":"cn.yunzhisheng.appmgr","code":"APP_EXIT","semantic":{"intent":{"name":"雷达"}},"history":"cn.yunzhisheng.appmgr","responseId":"672faccc24d644ac863be93646c13d3c"}
