### ISSUE TITLE
北极的天气现在反馈的是北京的天气

### ISSUE THREAD

**Issue by lvanli** [u-bug-collector/txz#11]
现在北极的天气在客户端和云之声网站测试结果一致，都是北京的天气。
但是实际上应该和以前一样，反馈没有找到城市编码或者其他类型的错误信息。

**Comment by u-bug-collector** [comment]
{"rc":1,"text":"北极的天气","service":"cn.yunzhisheng.weather","code":"FORECAST","semantic":{"intent":{"city":"北极","focusDate":"2017-02-06","topic":"WEATHER"}},"error":{"code":"INVALID_CITY","message":"没有找到北极的天气网城市编码，无法获取天气。"},"history":"cn.yunzhisheng.weather","responseId":"25e9ca4a66e9494d912c5323126c2b1b"}

DONE
