### ISSUE TITLE
普通聊天返回结果里面有null

### ISSUE THREAD

**Issue by lvanli** [u-bug-collector/txz#12]
{
    "rc": 0,
    "text": "北京时间是19点32分32秒",
    "service": "cn.yunzhisheng.chat",
    "code": "ANSWER",
    "general": {
        "type": "T",
        "text": "很抱歉，没有查到null的放假信息。",
        "style": "calendar"
    },
    "history": "cn.yunzhisheng.chat",
    "responseId": "16f3338083d047ab9696a1fbea2c0e79"
}

**Comment by u-bug-collector** [comment]
预计在2月底的版本中，进行修复。

**Comment by u-bug-collector** [comment]
{"rc":0,"text":"北京时间是10点32分32秒","service":"cn.yunzhisheng.chat","code":"ANSWER","general":{"type":"T","text":"搞不懂哎。","style":"calendar"},"history":"cn.yunzhisheng.chat","responseId":"c65b345304af417ea254b6633404c1ce"}
