### ISSUE TITLE
水口花园堵不堵返回的是导航场景

### ISSUE THREAD

**Issue by xiaohong001** [u-bug-collector/txz#14]
{
"rc": 0,
"text": "水口花园堵不堵",
"service": "cn.yunzhisheng.map",
"code": "ROUTE",
-"semantic": {
-"intent": {
"fromPOI": "CURRENT_LOC",
"fromCity": "CURRENT_CITY",
"toPOI": "水口花园堵",
"toCity": "CURRENT_CITY",
"pathPoints": [ ]
},
"normalHeader": "正在为您查找去水口花园堵的路线"
},
-"general": {
"type": "T",
"text": "正在为您查找去水口花园堵的路线"
},
"history": "cn.yunzhisheng.map",
"responseId": "dc57a1a457a647d983e7136aed1274e4"
}

**Comment by u-bug-collector** [comment]
{"rc":0,"text":"水口花园堵不堵","service":"cn.yunzhisheng.traffic","code":"TRAFFIC_QUERY","semantic":{"intent":{"city":"CURRENT_CITY","road":"水口花园"}},"history":"cn.yunzhisheng.traffic","responseId":"36627d5091b74f769a7fbb6411a4f0ef"}
