### ISSUE TITLE
期望增加“FM发射到XXX”说法

### ISSUE THREAD

**Issue by xiaohong001** [u-bug-collector/txz#15]
{
"rc": 0,
"text": "FM发射到99.5",
"service": "cn.yunzhisheng.chat",
"code": "ANSWER",
-"general": {
"type": "T",
"text": "调频可以这样说：收听中国之声",
"style": "unsupport"
},
"history": "cn.yunzhisheng.chat",
"responseId": "fbd48e5df930432fbb462cfbd9bb1fe5"
}
期望增加“FM发射到XXX”说法

**Comment by u-bug-collector** [comment]
目标：等价到“调频99.5”

**Comment by u-bug-collector** [comment]
时光带不走的信念一如既往 

![image](https://cloud.githubusercontent.com/assets/20939999/23932136/4b018e4e-0971-11e7-8a74-a176feb7e7d4.png)
