### ISSUE TITLE
高晓松的晓说是电台节目

### ISSUE THREAD

**Issue by xiaohong001** [u-bug-collector/txz#26]
{
"rc": 0,
"text": "播放高晓松的晓说",
"service": "cn.yunzhisheng.music",
"code": "SEARCH_SONG",
-
"semantic": {
-
"intent": {
"artist": "高晓松",
"song": "晓说",
"keyword": "高晓松 晓说"
}
},
"history": "cn.yunzhisheng.music",
"responseId": "c840a8dabd814dadb0cea7761b6013b2"
}
高晓松的晓说是电台节目

**Comment by u-bug-collector** [comment]
{"rc":0,"text":"高晓松的晓说","service":"cn.yunzhisheng.audio","code":"SEARCH_ALBUM","semantic":{"intent":{"artist":"高晓松","album":"晓松奇谈","keyword":"晓说 高晓松"}},"history":"cn.yunzhisheng.audio","responseId":"a2c433f005704ef39303b6221fba0ffb"}
