### ISSUE TITLE
播放红蔷薇，走的是聊天场景

### ISSUE THREAD

**Issue by xiaohong001** [u-bug-collector/txz#28]
{
"rc": 0,
"text": "播放红蔷薇",
"service": "cn.yunzhisheng.chat",
"code": "ANSWER",
-
"general": {
"type": "T",
"text": "红蔷薇 牛峤 唐\t晓啼珠露浑无力 绣簇罗襦不著行 若缀寿阳公主额 六宫争肯学梅妆",
"style": "poem"
},
"history": "cn.yunzhisheng.chat",
"responseId": "aa7b6fadfb054444b8626ae6d3f3ac7a"
}
这是一首诗歌

**Comment by u-bug-collector** [comment]
这是一首诗歌，算正确。
