### ISSUE TITLE
打开公众号走的是联系人场景

### ISSUE THREAD

**Issue by xiaohong001** [u-bug-collector/txz#29]
{
"rc": 0,
"text": "打开公众号",
"service": "cn.yunzhisheng.contact",
"code": "CONTACT_SEARCH",
-"semantic": {
-"intent": {
"name": "家"
}
},
"history": "cn.yunzhisheng.contact",
"responseId": "155663ae8aff4426ae3a9b916fe22761"
}
打开公众号走的是联系人场景

**Comment by xiaohong001** [comment]
期望结果：与打开app的场景类似
{
"rc": 0,
"text": "打开世界之窗",
"service": "cn.yunzhisheng.appmgr",
"code": "APP_LAUNCH",
-"semantic": {
-"intent": {
"name": "世界之窗"
}
},
"history": "cn.yunzhisheng.appmgr",
"responseId": "4edbcf17dfa3487ea4e84adab55ba479"
}

**Comment by u-bug-collector** [comment]
{"rc":0,"text":"打开公众号","service":"cn.yunzhisheng.appmgr","code":"APP_LAUNCH","semantic":{"intent":{"name":"公众号"}},"history":"cn.yunzhisheng.appmgr","responseId":"77147e69a069446d8c940a55823b511c"}
