### ISSUE TITLE
商丘的pm2.5，提示不支持查询商丘今天的空气质量指数

### ISSUE THREAD

**Issue by xiaohong001** [u-bug-collector/txz#30]
商丘的pm2.5，提示不支持查询商丘今天的空气质量指数，希望支持

{
"rc": 0,
"text": "商丘的pm2.5",
"service": "cn.yunzhisheng.weather",
"code": "FORECAST",
-"semantic": {
-"intent": {
"province": "河南省",
"city": "商丘市",
"cityCode": "101181001",
"focusDate": "2017-04-22",
"topic": "AIR_QUALITY"
}
},
-"data": {
"header": "抱歉，不支持查询商丘今天的空气质量指数。商丘今天天气情况是：晴，10至23℃，微风。",

**Comment by u-bug-collector** [comment]
缺乏数据源。
如果有可用的API接口，可提供出来。

**Comment by xiaohong001** [comment]
缺乏数据源的时候，可不可以不要播报之前的，“抱歉，不支持查询商丘今天的空气质量指数。”
