### ISSUE TITLE
导航去小蛮腰，toPOI的值不对

### ISSUE THREAD

**Issue by xiaohong001** [u-bug-collector/txz#31]
导航去小蛮腰，toPOI的值不对，希望能正确解析出目的地
{
"rc": 0,
"text": "导航去小蛮腰",
"service": "cn.yunzhisheng.map",
"code": "ROUTE",
-"semantic": {
-"intent": {
"fromPOI": "CURRENT_LOC",
"fromCity": "CURRENT_CITY",
"toPOI": "CURRENT_LOC",
"toCity": "CURRENT_CITY",
"method": "CAR",
"pathPoints": [ ]
},
"normalHeader": "正在为您查找路线"
},
-"general": {
"type": "T",
"text": "正在为您查找路线"
},
"history": "cn.yunzhisheng.map",
"responseId": "603b4a78e4f54d779898f4c0e91f5630"
}

**Comment by u-bug-collector** [comment]
{"rc":0,"text":"导航到小蛮腰","service":"cn.yunzhisheng.map","code":"ROUTE","semantic":{"intent":{"fromPOI":"CURRENT_LOC","fromCity":"CURRENT_CITY","toPOI":"广州塔","toCity":"广州市","method":"CAR","pathPoints":[]},"normalHeader":"正在为您查找去广州塔的路线"},"general":{"type":"T","text":"正在为您查找去广州塔的路线"},"history":"cn.yunzhisheng.map","responseId":"16eb2878535d43e39e8858862b0b5b9d"}
