### ISSUE TITLE
中国的美食，希望将场景改成百科

### ISSUE THREAD

**Issue by xiaohong001** [u-bug-collector/txz#32]
中国的美食，希望将场景改成百科
{
"rc": 0,
"text": "中国的美食",
"service": "cn.yunzhisheng.localsearch",
"code": "BUSINESS_SEARCH",
-"semantic": {
-"intent": {
"category": "美食",
"sortBiz": 1,
"city": "深圳市",
"poi": "中国"
}
},
"history": "cn.yunzhisheng.localsearch",
"responseId": "153659aa9a7246a69559e9bfb05d0378"
}

**Comment by u-bug-collector** [comment]
请在Appkey的管理界面，增加FAQ
