### ISSUE TITLE
给亮发个微信，没有给出name字段

### ISSUE THREAD

**Issue by xiaohong001** [u-bug-collector/txz#33]
给亮发个微信，没有给出name字段
{
"rc": 0,
"text": "给亮发个微信",
"service": "cn.yunzhisheng.sms",
"code": "SEND_WECHAT_MSG",
-"semantic": {
"intent": { }
},
"history": "cn.yunzhisheng.sms",
"responseId": "03923dec44084ec7a9dbae08b2831a4e"
}

**Comment by u-bug-collector** [comment]
单字姓名的姓名识别，需要上传联系人通信录。 请参考SDK中的接口，上传通信录。
