### ISSUE TITLE
微信给同行者，不能把name解析出来

### ISSUE THREAD

**Issue by xiaohong001** [u-bug-collector/txz#41]
{
"rc": 0,
"text": "微信给同行者",
"service": "cn.yunzhisheng.sms",
"code": "SEND_WECHAT_MSG",
-"semantic": {
"intent": { }
},
"history": "cn.yunzhisheng.sms",
"responseId": "2e1bcae94f0f407cbb30f27e60addf06"
}
没有把name同行者解析出来，期望可以解析出来

**Comment by u-bug-collector** [comment]
请确认下，“同行者”这个词，是否已经通过SDK接口上传给语义服务。
