### ISSUE TITLE
播放九千九百九十九朵玫瑰，解析出来是聊天场景

### ISSUE THREAD

**Issue by xiaohong001** [u-bug-collector/txz#43]
{
"rc": 0,
"text": "播放九千九百九十九朵玫瑰",
"service": "cn.yunzhisheng.chat",
"code": "ANSWER",
-"general": {
"type": "T",
"text": "ti:九百九十九朵玫瑰] [ar:邰正宵] 往事如风,痴心只是难懂 借酒相送,送不走身影蒙蒙 烛光投影,映不出你颜容",
"style": "CQA"
},
"history": "cn.yunzhisheng.chat",
"responseId": "ee1e5d9e95af4709984892e0810d994b"
}

期望结果，“九千九百九十九朵玫瑰”是一首歌曲，希望解析成音乐场景

**Comment by u-bug-collector** [comment]
已支持。
九千九百九十九朵玫瑰  => 九百九十九朵玫瑰
