### ISSUE TITLE
回家领域BUG

### ISSUE THREAD

**Issue by gracecai888** [u-bug-collector/txz#5]
优先级：中 [高中低]
BUG描述： 声控“下班回家”
返回结果： "周日，这么晚下班。好拼。"
期望：{
"rc": 0,
"text": "我要回家",
"service": "cn.yunzhisheng.map",
"code": "ROUTE",
-"semantic": {
-"intent": {
"fromPOI": "CURRENT_LOC",
"fromCity": "CURRENT_CITY",
"toPOI": "LOC_HOME",
"toCity": "CURRENT_CITY",
"pathPoints": [ ]
},
"normalHeader": "正在为您查找回家的路线"
},
"history": "cn.yunzhisheng.map",
"responseId": "e9ecff0e5eb448189062919db69020bb"
}
期望解决日期: 2016年8月11日

**Comment by gracecai888** [comment]
优先级：中 [高中低]
BUG描述： 声控“咱们回家吧”
返回结果："好的回家么么哒美女我们再也不见了"
期望：{
"rc": 0,
"text": "我要回家",
"service": "cn.yunzhisheng.map",
"code": "ROUTE",
-"semantic": {
-"intent": {
"fromPOI": "CURRENT_LOC",
"fromCity": "CURRENT_CITY",
"toPOI": "LOC_HOME",
"toCity": "CURRENT_CITY",
"pathPoints": [ ]
},
"normalHeader": "正在为您查找回家的路线"
},
"history": "cn.yunzhisheng.map",
"responseId": "e9ecff0e5eb448189062919db69020bb"
}
期望解决日期: 2016年8月11日

**Comment by u-bug-collector** [comment]
难度有些大。
这些聊天倾向性非常强的语句，如何与导航操控区分开，是个难题。
目前正在研究相关方案。
本任务，优先级暂时降低

**Comment by u-bug-collector** [comment]
fixed #5

**Comment by lvanli** [comment]
已验证
