### ISSUE TITLE
听郭德纲的相声，反馈：不支持有声读物服务

### ISSUE THREAD

**Issue by lvanli** [u-bug-collector/txz#7]
【操作步骤】 
如果是非电台key 
我要听郭德纲的相声是可以的 
但是说：听郭德纲的相声却不行 

如果是电台key 
听郭德纲的相声也是可以的 

"rc": 0, 
"text": "听郭德纲的相声", 
"service": "cn.yunzhisheng.chat", 
"code": "ANSWER", 
-"general": { 
"type": "T", 
"text": "不支持有声读物服务", 
"style": "unsupport" 
}, 
"history": "cn.yunzhisheng.chat", 
"responseId": "63df87f7a9e0488492830a0ea3ed7bca" 
} 

【期望结果】 
应该走muisc场景

**Comment by u-bug-collector** [comment]
@lvanli 这个我在QQ讨论组里说过了，需要你们关联有声读物领域。

`
2016/12/30 9:51:02
郭德纲相声的事情， 请关联 有声读物。
小李广 2016/12/30 9:51:52
在不关联的时候说我要听郭德纲的相声是可以走到音乐场景的呀

BOB 2016/12/30 9:52:05
不保证。

BOB 2016/12/30 9:52:08
这不是音乐

BOB 2016/12/30 9:52:36
上次谈论过 是否关联有声读物 的问题， 没有下文了。
你们得考虑下，这类问题，该如何系统性解决。
2016/12/30 9:56:07
BOB 2016/12/30 9:56:07
@小李广 
小李广 2016/12/30 9:56:32
我们内部讨论下

BOB 2016/12/30 9:56:51
嗯。
10:35:03
`
