### ISSUE TITLE
说上证指数，概率性没有返回mChangeRate字段

### ISSUE THREAD

**Issue by lvanli** [u-bug-collector/txz#8]
未返回mChangeRate字段的请求如下：
{"nluProcessTime":"40","rc":0,"text":"上证指数","service":"cn.yunzhisheng.stock","code":"STOCK_INFO","semantic":{"intent":{"id":"000001","name":"上证指数","exchange":"sh"}},"data":{"result":{"mChartImgUrl":"http://chart.jrjimg.cn/pngdata/minpic/pic300i/000001.png","mName":"上证指数","mCode":"sh000001","mCurrentPrice":"3102.24","mChangeAmount":"-12.43","mHighestPrice":"3118.78","mLowestPrice":"3094.55","mtradingVolume":"13,572,708,700股","mUpdateTime":"2016-12-28 15:00:05","mYesterdayClosingPrice":"3114.66","mTodayOpeningPrice":"3113.77","errorCode":0,"dataSourceName":"JINRONGJIE"}},"general":{"type":"T","text":"当前上证指数是：3102.24点"},"history":"cn.yunzhisheng.stock","responseId":"81e65997ca754aceb6ce5a9886f316fd"}

**Comment by u-bug-collector** [comment]
已提交给相应的同事，进入处理流程了。

**Comment by u-bug-collector** [comment]
DONE

**Comment by u-bug-collector** [comment]
@lvanli
