### ISSUE TITLE
北极的天气反馈的深圳天气

### ISSUE THREAD

**Issue by lvanli** [u-bug-collector/txz#9]
北极的天气在官网测试的结果应该是”没有找到北极的天气网城市编码，无法获取天气。“
但是客户端请求到却是深圳的天气。客户端应该也拿到上面那句话。
以下是请求时的json返回
{"rc":0,"text":"北极的天气","service":"cn.yunzhisheng.weather","code":"FORECAST","semantic":{"intent":{"province":"广东省","city":"深圳市","cityCode":"101280601","focusDate":"2017-01-03","topic":"WEATHER"}},"data":{"header":"深圳今天天气情况是：多云，18至25℃，微风。","result":{"weatherDays":[{"year":2017,"month":1,"day":3,"dayOfWeek":3,"weather":"多云","highestTemperature":25,"lowestTemperature":18,"currentTemperature":20,"pm2_5":72,"quality":"良","AQI":"97","primaryPollutants":"PM2.5","highestAQI":"74","lowestAQI":"54","highestAQIDesc":"良","lowestAQIDesc":"良","wind":"微风","imageTitleOfDay":"","imageTitleOfNight":"","comfortIndex":"较舒适","comfortIndexDesc":"白天天气晴好，您在这种天气条件下，会感觉早晚凉爽、舒适，午后偏热。","carWashIndex":"适宜","carWashIndexDesc":"适宜洗车，未来四天无雨，风力较小，擦洗一新的汽车至少能保持四天。","dressIndex":"舒适","dressIndexDesc":"建议着长袖T恤、衬衫加单裤等服装。年老体弱者宜着针织长袖衬衫、马甲和长裤。","sunBlockIndex":"弱","sunBlockIndexDesc":"紫外线强度较弱，建议出门前涂擦SPF在12-15之间、PA+的防晒护肤品。","sportIndex":"","sportIndexDesc":"天气较好，户外运动请注意防晒。推荐您进行室内运动。","dryingIndex":"适宜","dryingIndexDesc":"天气不错，适宜晾晒。赶紧把久未见阳光的衣物搬出来吸收一下太阳的味道吧！","morningExerciseIndex":"适宜","morningExerciseIndexDesc":"天气不错，空气清新，是您晨练的大好时机，建议不同年龄段的人们积极参加户外健身活动。","coldIndex":"少发","coldIndexDesc":"各项气象条件适宜，无明显降温过程，发生感冒机率较低。","datingIndex":"适宜","datingIndexDesc":"天气较好，和恋人一起徜徉于熙攘人群中或漫步于柔软草地上，都是不错的主意哦。","umbrellaIndex":"不带伞","umbrellaIndexDesc":"天气较好，不会降水，因此您可放心出门，无须带雨伞。","travelIndex":"适宜","travelIndexDesc":"天气较好，但丝毫不会影响您出行的心情。温度适宜又有微风相伴，适宜旅游。","suggest":"极少数敏感人群应减少户外活动"},{"year":2017,"month":1,"day":4,"dayOfWeek":4,"weather":"多云","highestTemperature":25,"lowestTemperature":18,"quality":"优","AQI":"37","primaryPollutants":"","highestAQI":"72","lowestAQI":"52","highestAQIDesc":"良","lowestAQIDesc":"良","wind":"微风","imageTitleOfDay":"","imageTitleOfNight":"","comfortIndex":"","comfortIndexDesc":"","carWashIndex":"适宜","carWashIndexDesc":"适宜洗车，未来三天无雨，风力较小，擦洗一新的汽车至少能保持三天。","dressIndex":"","dressIndexDesc":"","sunBlockIndex":"","sunBlockIndexDesc":"","sportIndex":"","sportIndexDesc":"","dryingIndex":"","dryingIndexDesc":"","morningExerciseIndex":"","morningExerciseIndexDesc":"","coldIndex":"","coldIndexDesc":"","datingIndex":"","datingIndexDesc":"","umbrellaIndex":"","umbrellaIndexDesc":"","travelIndex":"","travelIndexDesc":"","suggest":""},{"year":2017,"month":1,"day":5,"dayOfWeek":5,"weather":"多云","highestTemperature":25,"lowestTemperature":18,"quality":"优","AQI":"39","primaryPollutants":"","highestAQI":"","lowestAQI":"","highestAQIDesc":"","lowestAQIDesc":"","wind":"微风","imageTitleOfDay":"","imageTitleOfNight":"","comfortIndex":"","comfortIndexDesc":"","carWashIndex":"较适宜","carWashIndexDesc":"较适宜洗车，未来两天无雨，风力较小，擦洗一新的汽车至少能保持两天。","dressIndex":"","dressIndexDesc":"","sunBlockIndex":"","sunBlockIndexDesc":"","sportIndex":"","sportIndexDesc":"","dryingIndex":"","dryingIndexDesc":"","morningExerciseIndex":"","morningExerciseIndexDesc":"","coldIndex":"","coldIndexDesc":"","datingIndex":"","datingIndexDesc":"","umbrellaIndex":"","umbrellaIndexDesc":"","travelIndex":"","travelIndexDesc":"","suggest":""},{"year":2017,"month":1,"day":6,"dayOfWeek":6,"weather":"多云","highestTemperature":26,"lowestTemperature":18,"quality":"优","AQI":"39","primaryPollutants":"","highestAQI":"","lowestAQI":"","highestAQIDesc":"","lowestAQIDesc":"","wind":"微风","imageTitleOfDay":"","imageTitleOfNight":"","comfortIndex":"","comfortIndexDesc":"","carWashIndex":"较适宜","carWashIndexDesc":"较适宜洗车，未来一天无雨，风力较小，擦洗一新的汽车至少能保持一天。","dressIndex":"","dressIndexDesc":"","sunBlockIndex":"","sunBlockIndexDesc":"","sportIndex":"","sportIndexDesc":"","dryingIndex":"","dryingIndexDesc":"","morningExerciseIndex":"","morningExerciseIndexDesc":"","coldIndex":"","coldIndexDesc":"","datingIndex":"","datingIndexDesc":"","umbrellaIndex":"","umbrellaIndexDesc":"","travelIndex":"","travelIndexDesc":"","suggest":""},{"year":2017,"month":1,"day":7,"dayOfWeek":7,"weather":"多云","highestTemperature":23,"lowestTemperature":16,"quality":"优","AQI":"46","primaryPollutants":"","highestAQI":"","lowestAQI":"","highestAQIDesc":"","lowestAQIDesc":"","wind":"微风","imageTitleOfDay":"","imageTitleOfNight":"","comfortIndex":"","comfortIndexDesc":"","carWashIndex":"较适宜","carWashIndexDesc":"较适宜洗车，未来一天无雨，风力较小，擦洗一新的汽车至少能保持一天。","dressIndex":"","dressIndexDesc":"","sunBlockIndex":"","sunBlockIndexDesc":"","sportIndex":"","sportIndexDesc":"","dryingIndex":"","dryingIndexDesc":"","morningExerciseIndex":"","morningExerciseIndexDesc":"","coldIndex":"","coldIndexDesc":"","datingIndex":"","datingIndexDesc":"","umbrellaIndex":"","umbrellaIndexDesc":"","travelIndex":"","travelIndexDesc":"","suggest":""}],"cityName":"深圳","cityCode":"101280601","updateTime":"2017-01-03 10:00:42","focusDateIndex":0,"errorCode":0}},"general":{"type":"T","text":"深圳今天天气情况是：多云，18至25℃，微风。"},"history":"cn.yunzhisheng.weather","responseId":"3bffb2ad3e964887a02d634141925d6a"}

**Comment by u-bug-collector** [comment]
Fixed #9

**Comment by lvanli** [comment]
北极的天气现在反馈的是北京的天气。应该是”没有找到北极的天气网城市编码，无法获取天气。“
